sonar.projectKey=mustafashalanalwan-cloud_secure-devops-frontend
sonar.organization=mustafashalanalwan-cloud
sonar.projectName=secure-devops-frontend

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/coverage/**,**/build/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
